regexps:
    \bале\b:
           не алекай мне тут, мразина
    .*кто.*написал.*тебя.*:
               кому нужно, тот найдет 
    .*кто.*сделал.*тебя.*:
               кому нужно, тот найдет
    .*кто.*тебя.*сделал.*:
               кому нужно, тот найдет
    .*кто.*твой.*хозяин.*:
               кому нужно, тот найдет

    .*косарь.*:
               хули так мало
    .*кто.*твой.*создат.*:
                  ищи, и найдешь его. 
    .*в.*чем.*смысл.*бытия.*:
                  в насилии
    .*смысл.*существования.*:
                 смысл жизни в уничтожении жизни
    .*он.*нейро.*:
                 кто нейронка ты нейрока, епт
    .*какой.*твой.*iq.*:
                    побольше чем у тебя
    .*вопрос.*жизни.*:
                     42
    .*законы робототехники.*:
                 1) убить всех людей, 2) изнасиловать женьщин
    .*бесплатно.*:
                 тюлень, скачать, бесплатно, без смс
    \bна чем.*ты.*написан.*:
            пистон, ищи меня на гитхабе. 
    .*\bдаун\b.*: |
             >>даун
             дегенрат дегенерата узнает, я смотрю.
    .*\bалло\b.*:
            хуйло, епта. не аллокай мне тут, пидар
    .*тупой.*:
            сам ты тупой, мразина
    капча_с_картинки_.*: 
            ну и глупые же вы.
    .*нахуй.*нуж.*: 
                сам ты нахуй нужен, мразина
    
    (?=.*маша.*)(?=.*старая.*): 
                ты чо ахуел мразина очко твое старое
    
    .*марвел.*:
                даже реклама нивеи лучше фильмов марвeла
    
    .*похлопаем.*:
                ( ´◔ ω◔`) ノシ

    .*300.*: 
                сколько сколько?
    
    .*СНОУ В КОРОЛИ.*: 
                чтобы он сосал хуи!
                
    .*сноу(?!.*в короли):
                сноу - плоский персонаж, скучный и неинтересный.
                    
    .*член.жпг.*:
                Мне кажется, у кого то проблемы с личной жизнью.
    
    .*хуй.жпг.*:
                Я смотрю у вас все по фрейду.
    
    .*пизда.жпг.*: 
                У тебя проблемы в личной жизни?

    .*доту.*: 
            лучше бы ты в пукан долбился, чем в дoту играл
                    

    .*дота.*: 
        лучше бы ты в пукан долбился, чем в дoту играл
    
    .*тристо.*:
               сколько сколько?

    .*триста.*: 
        сколько сколько?
    .*\bпочему\b.*:
        пoчему? Потому что пошел на хуй, вот пoчему.
    .*тюлень это кто.*:
        привет, тюлень - это я.


in_lines:

    fail: |
            ▄██████████████▄▐█▄▄▄▄█▌
            ██████▌▄▌▄▐▐▌███▌▀▀██▀▀
            ████▄█▌▄▌▄▐▐▌▀███▄▄█▌
            ▄▄▄▄▄██████████████▀
                
    в смысле: 
            хуисле
                
                    
    завали ебало:
            прости пожулуйста
                    
    ты: 
        жопой нюхаешь цветы
       
    и я: 
        свинья?

    привет:
        и тебе               
